Fixed NullReferenceException when files are imported for the first time.
The problem was that Unity imports the surfshader assets prior importing the shader templates, causing Resources.Load to fail. I've replaced Resources.Load with File.ReadAllText to workaround this problem.

NullReferenceException: Object reference not set to an instance of an object
  at ShaderBuilder.Build in ShaderBuilder.cs:15